# Generated by Django 5.0.6 on 2024-05-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastnotification',
            options={'ordering': ['-broadcast_on']},
        ),
    ]
