# Generated by Django 5.0.6 on 2024-05-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_broadcastnotification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastnotification',
            name='level',
            field=models.TextField(default='Moderate'),
        ),
    ]
